# General stuff
name: Lexteam
url: https://www.lexteam.xyz
description: Lexteam is a small team consisting of three developers, of which strive to create new and innovative software.

# These files are excluded from the Jekyll build
# With node, this is rather important ;)
exclude:
  - etc
  - violet/src
  - violet/node_modules
  - violet/package.json
  - violet/cli.js
  - violet/gulpfile.js
  - violet/README.md
  - violet/changelog.txt
  - node_modules
  - gulpfile.js
  - kabosu.sh
  - package.json

# Extra plugins
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
