# General stuff
name: Lexteam
url: https://www.lexteam.xyz

exclude:
  - violet/source
  - violet/node_modules
  - violet/package.json
  - violet/violet.js
  - violet/README.md
  - violet/changelog.txt
  - indigo/src
  - indigo/node_modules
  - indigo/package.json
  - indigo/indigo.js
  - indigo/README.md
  - indigo/changelog.txt
  - node_modules
  - gulpfile.js
  - package.json

# Extra plugins
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
