# General stuff
name: Lexteam
url: https://www.lexteam.xyz

exclude:
  - violet/src
  - violet/node_modules
  - violet/package.json
  - violet/cli.js
  - violet/README.md
  - violet/changelog.txt
  - node_modules
  - gulpfile.js
  - package.json

# Extra plugins
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
